server:
  port: 7777


mybatis:
        config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
        type-aliases-package: org.java.entity                     # 所有Entity别名类所在包
        #mapper-locations:
        #- classpath:mybatis/mapper/**/*.xml                       # mapper映射文件



spring:
   application:
    name: transport-web
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
#    url: jdbc:mysql://119.29.128.90:3306/trans?useUnicode=true&characterEncoding=utf8
    url: jdbc:mysql://localhost:3306/trans?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

    thymeleaf:
        #缓冲的配置
        cache: false
        check-template: true
        check-template-location: true
        #开启MVC thymeleaf 视图解析
        enabled: true
        encoding: utf-8
        mode: HTML5
        prefix: classpath:/templates/
        suffix: .html

    jpa:
          hibernate:
            ddl-auto: update
            show-sql: true

 #pagehelper分页插件配置
    pagehelper:
      helper-dialect: mysql
      reasonable: true
      support-methods-arguments: true
      params: countSql